import { Inter } from "next/font/google";
import "./globals.css";
import TenStackQuery from "@/components/TenStackQuery";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <TenStackQuery>{children}</TenStackQuery>
      </body>
    </html>
  );
}
